import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import api from '../services/api';
import { useToast } from '../components/Toast';
import { BrainCircuit, Eye, Sparkles, TrendingUp } from 'lucide-react';

const PredictionHistory = () => {
  const [history, setHistory] = useState([]);
  const [loading, setLoading] = useState(true);
  const { showToast } = useToast();

  useEffect(() => {
    fetchHistory();
  }, []);

  const fetchHistory = async () => {
    try {
      const response = await api.get('/history');
      setHistory(response.data);
    } catch (err) {
      showToast('Failed to load AI prediction history records.', 'error');
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return (
      <div className="spinner-container">
        <div className="spinner"></div>
      </div>
    );
  }

  const getPredictionClass = (pred) => {
    switch (pred?.toLowerCase()) {
      case 'eligible':
        return 'badge-eligible';
      case 'moderate risk':
        return 'badge-moderate';
      default:
        return 'badge-highrisk';
    }
  };

  return (
    <div className="page-container">
      <div style={{ marginBottom: '2rem' }}>
        <h1 style={{ fontSize: '1.75rem', fontWeight: '700' }}>AI Prediction History</h1>
        <p style={{ color: 'var(--text-secondary)', fontSize: '0.9rem' }}>Review all eligibility assessments generated by our rule-based AI engine.</p>
      </div>

      {history.length > 0 ? (
        <div className="card">
          <h3 className="card-title">
            <BrainCircuit size={20} style={{ color: 'var(--primary)' }} />
            History Log ({history.length} runs)
          </h3>
          
          <div className="table-container" style={{ marginTop: '1rem' }}>
            <table className="data-table">
              <thead>
                <tr>
                  <th>Run ID</th>
                  <th>Verdict</th>
                  <th>Risk Score</th>
                  <th>Confidence</th>
                  <th>Underwriting Rationale</th>
                  <th>Filing Date</th>
                  <th style={{ textAlign: 'right' }}>Action</th>
                </tr>
              </thead>
              <tbody>
                {history.map((run) => (
                  <tr key={run.id}>
                    <td>#{run.id}</td>
                    <td>
                      <span className={`badge ${getPredictionClass(run.prediction)}`}>
                        {run.prediction}
                      </span>
                    </td>
                    <td>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
                        <span style={{ fontWeight: '600' }}>{run.risk_score}%</span>
                      </div>
                    </td>
                    <td>{run.confidence}%</td>
                    <td style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', maxWidth: '280px', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                      {run.reason}
                    </td>
                    <td>{new Date(run.created_at).toLocaleString()}</td>
                    <td style={{ textAlign: 'right' }}>
                      {run.loan_id ? (
                        <Link 
                          to={`/prediction-result/${run.loan_id}`} 
                          className="btn btn-secondary" 
                          style={{ padding: '0.4rem 0.8rem', fontSize: '0.8rem' }}
                        >
                          <Eye size={14} />
                          <span>View Detail</span>
                        </Link>
                      ) : (
                        <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>Calculator Run</span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      ) : (
        <div className="card text-center" style={{ padding: '4rem 2rem' }}>
          <div style={{ color: 'var(--text-muted)', marginBottom: '1.5rem' }}>
            <BrainCircuit size={48} style={{ strokeWidth: 1.5 }} />
          </div>
          <h3 style={{ fontSize: '1.25rem', fontWeight: '600', marginBottom: '0.5rem' }}>No AI Runs Recorded</h3>
          <p style={{ color: 'var(--text-secondary)', maxWidth: '400px', margin: '0 auto 1.5rem' }}>
            Your history log will fill as soon as you apply for a relief loan or run predictions.
          </p>
          <Link to="/loan/apply" className="btn btn-primary">
            Apply Now
          </Link>
        </div>
      )}
    </div>
  );
};

export default PredictionHistory;
